
server:
  port: 8081
logging:
  level:
    root: info
    com.swan.log.test: info
swan:
  log:
    max-length: 30
    arg-max-length: 10
    dir: /tmp/swan/log
    override-suffix: ...
    max-custom-files: 144
    max-error-files: 6
spring:
  application:
    name: test-swagger-starter
  profiles:
    active: dev

knife4j:
  enable: true
  title: Swan Knife4j Starter
  description: 对 knife4j 的封装
  version: 2.0.0
  host: 127.0.0.1
  service-url: http://localhost:8081
  author: zongf
  global:
    name: all
    display-name: 全部
    common-parameters: token
    filter:
      paths-to-match: /**
  groups:
    - name: order                    # knife 分组列表已 group name 进行排序
      displayName: 订单接口组              # 分组名称
      pathsToMatch: /**             # 以路径分组
    - name: user
      displayName: 用户接口组
      pathsToMatch: /user/**
      commonParameters: token,requestId
  parameter-configs:
    - name: token
      type: String
      required: true
      location: header
      defaultValue: ''
      description: 请求token
      allowEmpty: false
    - name: requestId
      type: String
      required: true
      location: header
      defaultValue: ''
      description: 请求token
      allowEmpty: false


