
server:
  port: 8081
logging:
  level:
    root: info
    com.swan.log.test: info
swan:
  log:
    max-length: 30
    arg-max-length: 10
    dir: /tmp/swan/log
    override-suffix: ...
    max-custom-files: 144
    max-error-files: 6
spring:
  application:
    name: test-swan-knife4j-starter
  profiles:
    active: dev

knife4j:
  enable: true
  title: Swan Knife4j Starter
  description: 对 knife4j 的封装
  version: 2.0.0
  host: 127.0.0.1
  service-url: http://localhost:8081
  author: zongf
  parameter-configs:          # 参数配置
    - name: token             # 参数位置
      type: String            # 参数类型
      required: true          # 是否必填
      location: header        # 参数位置
      defaultValue: 'abc'        #
      description: 请求token   # 参数说明
      allowEmpty: false       # 是否允许为空
    - name: requestId
      type: String
      required: false
      location: header
      defaultValue: 'def'
      description: 请求token
      allowEmpty: false
  global:
    display-name: 全部
    common-parameters: token
    filter:
      paths-to-match: /**
  groups:
    - name: order                         # knife 分组列表已 group name 进行排序
      displayName: 订单接口组               # 分组名称
      filter:
        pathsToMatch: /order/**                   # 以路径分组
      common-parameters: requestId
    - name: user
      displayName: 用户接口组
      filter:
        pathsToMatch: /user/**
      commonParameters: token



