spring:
  application:
    name: test-wan-log-starter
logging:
    level:
      root: info
      com.swan.log.test: info
swan:
  log:
    max-length: 30
    arg-max-length: 10
    dir: /tmp/swan/log
    override-suffix: ...
    max-custom-files: 144
    max-error-files: 6

