spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swan-mybatis?serverTimezone=UTC&&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.swan.mybatis.po
  configuration:
    map-underscore-to-camel-case: true


server:
  port: 7080
logging:
  level:
    root: info
    com.swan.test.mybatis.mapper: debug
sboot:
  mybatis:
    log:
      enable: true
      mapperConfig:
        com.swan.test.mybatis.mapper.IAutoDelMapper: true
        com.swan.test.mybatis.mapper.IAutoDelVersionMapper: true
        com.swan.test.mybatis.mapper.IAutoMapper: true
        com.swan.test.mybatis.mapper.IAutoVersionMapper: true
        com.swan.test.mybatis.mapper.CustomMethodMapper: true
