spring:
  datasource:
    url: jdbc:mysql://localhost:3306/swan-mybatis?serverTimezone=UTC&&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.swan.mybatis.po
  configuration:
    map-underscore-to-camel-case: true
  log-mapper:
    enable: true
    path: target
    mappers: IAutoMapper


server:
  port: 7080
logging:
  level:
    root: info
    com.swan.test.mybatis.mapper: debug
