spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin               # 需要创建个 admin 用户
    password: admin
    virtual-host: rabbit-test     # 虚拟主机
    publisher-confirm-type: none #correlated
    publisher-returns: true
logging:
  level:
    root: info